### ISSUE TITLE
Unable to load Open WebUI after adding model to function's valves

### ISSUE THREAD

**Issue by yourmomdatestedcruz** [Haervwe/open-webui-tools#4]
Hi,

I added planner to my Open WebUI instance, and after adding a model ID in the valves for the function, I'm not able to load Open WebUI any more.

I'm running it in Docker, using the latest image version (0.5.2 at the time).

I'm trying to find where that function might be stored in the Docker container files so that I can remove it but I'm not sure where to look, or if that would even solve the issue?

Looking in the Docker console log, it looks like the issue is that I haven't defined an action model:

`2024-12-28 11:11:37 ACTION_MODEL
2024-12-28 11:11:37   Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
2024-12-28 11:11:37     For further information visit https://errors.pydantic.dev/2.9/v/string_type`

Any ideas?

**Comment by yourmomdatestedcruz** [comment]
Update: here is the full startup log I get when I try to access Open WebUI - attached.

How can I "uninstall" this function without the UI? I don't have an action model to point it to so I wouldn't be able to address the issue in the proper way here.

[Uploading docker_open_webui_launch_log.txt…]()

**Comment by Haervwe** [comment]
Hi just saw the issue, it must have saved some parameters wrongly, and prevents the UI to load, can you share the models name? Also if you wait does it start with the planner deactivated? The lastest changes in owui made me change some stuff, action model if is setted to default should take the same as the main model

**Comment by Haervwe** [comment]
Ok, so weird, if you know how to navigate on an SQL database, you might remove the function from the db, and restart owui, happened to.me.before, the error is weird I will fix it asap, but you mist remove the broken function from the db so it stops breaking the UI

**Comment by Haervwe** [comment]
fixed it , it was the default value setted to none, now it should wqork correctly, if you have trouble with deleting the function from the db, send me a msj on socials and we coordinate a call and i help you out. the lastest version here is fized, also on the hub

**Comment by Haervwe** [comment]
https://openwebui.com/f/haervwe/Planner/ the hub link , also hit me up for the deletion if needed

**Comment by Haervwe** [comment]
Hi! its fixed, was a the defaults setted to none , also fized another issues with the action model, if you have trouble deleting the function from the db hit me up on socials i can give you a hand, the function is updated here and on the HUB

**Comment by yourmomdatestedcruz** [comment]
Hey @Haervwe thanks!

I ended up re-installing owui entirely from scratch; couldn't get anything to work otherwise. I wouldn't have been able to get into SQL and delete the function and for the sake of saving a few setup tweaks I'd made, it wasn't worth getting that involved.

Appreciate the reactivity and that the issue is fixed now so that others won't run into it!
